### ISSUE TITLE
freight-add says package exists when $VARLIB is not writable

### ISSUE THREAD

**Issue by eswierk** [rcrowley/freight#48]
I'm using freight 0.3.5 (very nifty!). I added a bunch of packages to a repository as one user, which created directories in $VARLIB owned by that user. I then mistakenly tried adding another package as a different user, which couldn't write to $VARLIB. But instead of complaining about permissions, freight-add says

# [freight] apt/foo/bar already has baz_1.0_amd64.deb

even though baz clearly wasn't there. It took me a few minutes to figure that one out.

**Comment by rcrowley** [comment]
Oh, that's a bug!  Thank you for reporting it.  I'll get a fix out soon.

**Comment by rcrowley** [comment]
Well damn, `ln`(1) exits 1 no matter how it fails.  So let me think about it a bit more.  It will be very easy to just let `ln`(1) print its error message but I'd rather not leak unaffiliated error messages because it may confuse users.  Perhaps I'll capture the error message and massage the error message slightly.

Regardless, as you pointed out, it is masking why it fails in this scenario and I'd like to fix that.

**Comment by narcisgarcia** [comment]
(off topic) Should be the option to run: freight --version
Using v0.3.10

freight-add (without the -e option) currently doesn't return exitcode in error when says "# [freight] apt/distro already has package.deb"
